name: Create Pull Request

on:
  workflow_run:
    workflows: [ "Rust Test" ]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Fetch branches
        run: git fetch --all

      - name: Switch to the release branch
        run: git checkout release

      - name: Create Pull Request
        run: |
          if gh pr list --head release --base main --state open | grep -q .; then
            echo "A pull request from 'release' to 'main' already exists."
          else
            echo "Creating a new pull request from 'release' to 'main'..."
            gh pr create --title "Auto PR from release" \
                         --body "This PR was automatically created by GitHub Actions." \
                         --base main \
                         --head release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
