name: Create Pull Request

on:
  workflow_run:
    workflows: [ "Rust Test" ]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Pull Request
        run: |
          CURRENT_BRANCH="release"
          
          if [ "$GITHUB_REF_NAME" != "$CURRENT_BRANCH" ]; then
            echo "This workflow only runs from the '$CURRENT_BRANCH' branch. Skipping."
            exit 0
          fi
          
          if gh pr view "$CURRENT_BRANCH" --base main > /dev/null 2>&1; then
            echo "A pull request from '$CURRENT_BRANCH' to 'main' already exists."
          else
            echo "Creating a new pull request from '$CURRENT_BRANCH' to 'master'..."
            gh pr create --title "Auto PR from $CURRENT_BRANCH" \
                         --body "This PR was automatically created by GitHub Actions." \
                         --base main \
                         --head "$CURRENT_BRANCH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
