name: Create Pull Request

on:
  workflow_run:
    workflows: [ "Rust Test" ]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Switch to the release branch
        run: git checkout release

      - name: Set CURRENT_BRANCH
        run: echo "CURRENT_BRANCH=release" >> $GITHUB_ENV

      - name: Authenticate GH CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          git fetch origin main release
          
          # Skip if there is no difference
          if git diff --quiet origin/main..origin/release; then
            echo "No differences between release and main. Skipping PR creation."
            exit 0
          fi
          
          # Check if PR already exists.
          if gh pr list --head "$CURRENT_BRANCH" --base main --state open | grep -q "$CURRENT_BRANCH"; then
            echo "PR from $CURRENT_BRANCH to main already exists."
          else
            echo "Creating PR from $CURRENT_BRANCH to main..."
            gh pr create --title "Auto PR from $CURRENT_BRANCH" \
                         --body "This PR was automatically created by GitHub Actions." \
                         --base main \
                         --head "$CURRENT_BRANCH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
